version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-app
    ports:
      - "8888:8888"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis
  db:
    image: 'postgres'
    container_name: apivendas-db
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apivendas

  redis:
    image: 'bitnami/redis:latest'
    container_name: apivendas-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

